version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Replace with a strong, random password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  web:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root  # Not recommended for production!
      DB_PASSWORD: 1234  # Not recommended for production!
      DB_NAME: hackbuzz

volumes:
  db_data: {}
